### ISSUE TITLE
two errors in plot of windows

### ISSUE THREAD

**Issue by dj10086** [kevinblighe/E-MTAB-6141#1]
hi, I am trying to repeat the code you supplied, but found 2 errors in windows R. thanks in advance

1  'Gene\nZ-\nscore'  will give errors in windows, not like linux, windows does not support \n， maybe it connected with file name
2 one line code repeat in the following
`# row (gene) parameters
      cluster_rows = TRUE,
      show_row_dend = TRUE,
      #row_title = 'Statistically significant genes',
      row_title_side = 'left',
      row_title_gp = gpar(fontsize = 12,  fontface = 'bold'),
      row_title_rot = 90,
      show_row_names = FALSE,
      **row_names_gp = gpar(fontsize = 10, fontface = 'bold'),**
      row_names_side = 'left',
      row_dend_width = unit(25,'mm'),`

<br>

and I found the gene names font size is so big, I change the row_title_gp = gpar(fontsize = 1,  fontface = 'bold'), but does not make sense, how should I revise it?

and after change **Gene\nZ-\nscore** to Gene_Z--score, it outsided the plot area,
![image](https://user-images.githubusercontent.com/61576362/91878413-d713ff80-ecb1-11ea-8363-112994d4ddf7.png)

**Comment by kevinblighe** [comment]
For Windows, perhaps try `\r\n`

**Comment by dj10086** [comment]
no, it also does not work

**Comment by kevinblighe** [comment]
From where are you running R?  I have not tested the tutorial in R Studio because I do not use R Studio.

**Comment by dj10086** [comment]
I test all the code, now I revise the font in anno_mark, the font size becomes ok. but the line feed still can not be ok.
![image](https://user-images.githubusercontent.com/61576362/91916594-16614100-ecf0-11ea-8eb0-05fb468012f3.png)

**Comment by dj10086** [comment]
hmap <- Heatmap(heat,
                
                # split the genes / rows according to the PAM clusters
                split = pamClusters$clustering,
                cluster_row_slices = FALSE,
                **name = 'Gene Z-score',**  # must delete the \n in windows

**Comment by kevinblighe** [comment]
Strange. What about `\r`?

Can you elaborate on how you are using R? R Studio? R Server?

**Comment by dj10086** [comment]
R Studio and R in windows has beed tried
\n and \r\n has bedd tried.
does not work at all

**Comment by kevinblighe** [comment]
Really not sure what is happening. You can use a shorter name like 'Z-score', or change the following:

```
name = 'Gene Z-score',
legend_direction = 'horizontal
```
```

draw(hmap + genelabels,
    heatmap_legend_side = 'bottom',
    annotation_legend_side = 'right',
    row_sub_title_side = 'left')

```

**Comment by kevinblighe** [comment]
Well, any luck?

**Comment by kevinblighe** [comment]
No response
