### ISSUE TITLE
Processed normalized data of blood samples 

### ISSUE THREAD

**Issue by gyanmishra** [kevinblighe/E-MTAB-6141#3]
Hi Kevin,

Could you please provide the processed file having normalized count or RLD files for blood RNA-seq data. I am interested to look into correlation of few genes across samples. 

Thanks 
Gyan

**Comment by kevinblighe** [comment]
Hi @gyanmishra , these are accessible via this link: https://github.com/kevinblighe/E-MTAB-6141/tree/master/rdata
Please let me know if that is all that is required.
Kind regards,
Kevin

**Comment by gyanmishra** [comment]
Hi Kevin,

Thanks for yor reply. I could not find the normalized data related to RNA-seq of blood samples, colnames having sample id is realted to on synovium samples. 
see below image. 

Anyway, I have processed the raw fastq files from ArrayExpress. 

![Untitled-Jupyter-Notebook](https://user-images.githubusercontent.com/17849272/185556339-f32ff065-ee52-478e-898b-650a15beec1d.png)

**Comment by kevinblighe** [comment]
Ah, I see what you mean. This tutorial on Github only shows the data for synovium.
For the blood data, can you contact Myles from the address available here: https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-6141/
You can point to this Github issue when you contact Myles.

**Comment by gyanmishra** [comment]
Thanks Kevin, I will write to Myles for the datasets.
